tasks:
- name: Setup Dev Environment
  before: |
    npm i -g @aeternity/aeproject@^4.2.1
    npm i
  init: |
    aeproject env --nodeVersion v6.6.0 --compilerVersion v6.1.0
  command: |
    aeproject -V
    aeproject --help

vscode:
  extensions:
    - hackbg.sophia